# Fly.io configuration for DARCI
app = "darci"
primary_region = "ord"  # Chicago - change to your preferred region

[build]

[env]
  NODE_ENV = "production"
  DCLI_DB_PATH = "/data/darci.db"
  MANIFEST_DB_PATH = "/data/manifest.db"
  MANIFEST_INFO_PATH = "/data/manifest_info.json"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "darci_data"
  destination = "/data"
