# Fly.io configuration for DARCI
app = "darci"
primary_region = "bos"  # Boston - matches existing volume

[build]

[env]
  NODE_ENV = "production"
  DCLI_DB_PATH = "/data/dcli.sqlite3"
  MANIFEST_DB_PATH = "/data/manifest.sqlite3"
  MANIFEST_INFO_PATH = "/data/manifest_info.json"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[processes]
  web = "/app/docker-entrypoint.sh"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["web"]

[mounts]
  source = "data"
  destination = "/data"

# Cron jobs are now handled by Supercronic process
