# Fly.io configuration for DARCI
app = "darci"
primary_region = "ord"  # Chicago - change to your preferred region

[build]

[env]
  NODE_ENV = "production"
  DCLI_DB_PATH = "/data/darci.db"
  MANIFEST_DB_PATH = "/data/manifest.sqlite3"
  MANIFEST_INFO_PATH = "/data/manifest_info.json"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "/app/docker-entrypoint.sh"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "data"
  destination = "/data"

# Cron jobs for automated data syncing
[[cron]]
  schedule = "5 */12 * * *"  # Every 12 hours at 5 minutes past the hour
  command = "dclim -D /data/"

[[cron]]
  schedule = "*/30 * * * *"  # Every 30 minutes
  command = "dclisync -D /data/ --sync"
