# Fly.io configuration for DARCI
app = "darci"
primary_region = "ord"  # Chicago - change to your preferred region

[build]

[env]
  NODE_ENV = "production"
  DCLI_DB_PATH = "/data/dcli.sqlite3"
  MANIFEST_DB_PATH = "/data/manifest.sqlite3"
  MANIFEST_INFO_PATH = "/data/manifest_info.json"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[processes]
  web = "/app/docker-entrypoint.sh"
  cron = "/app/docker-cron-entrypoint.sh"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
  processes = ["web", "cron"]

[mounts]
  source = "data"
  destination = "/data"

# Cron jobs are now handled by Supercronic process
